import type { Metadata } from 'next';

import './globals.css';
import Link from 'next/link';
import { Nunito } from 'next/font/google';

const inter = Nunito({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gradient-to-b from-yellow-50 to-yellow-200`}>
        {children}
        <NavBar />
      </body>
    </html>
  );
}

export function NavBar() {
  return (
    <div className="flex text-med items-center justify-between mx-12">
      <Link
        className="border-solid border-2 bg-red-100 rounded-md border-red-400 p-2 m-2"
        href="./"
      >
        Logout
      </Link>
      <Link
        className="border-solid border-2 bg-red-100 rounded-md border-red-400 p-2 m-2"
        href="./calendar"
      >
        Calendar
      </Link>
      <Link
        className="border-solid border-2 bg-red-100 rounded-md border-red-400 p-2 m-2"
        href="./profile"
      >
        Profile
      </Link>
      <Link
        className="border-solid border-2 bg-red-100 rounded-md border-red-400 p-2 m-2"
        href="./stats"
      >
        Stats
      </Link>
    </div>
  );
}
